"""
NOC Tune - Configuration Handler

Handles reading and writing configuration files.
"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional


DEFAULT_CONFIG = {
    'TARGETS': ['https://www.google.com'],
    'SAMPLE_COUNT': 5,
    'DELAY_SECONDS': 2,
    'PING_DURATION': 10,
    'AUTO_CONTRIBUTE': True,
    'SIGNAL_THRESHOLD_DBM': -70,
    'TTFB_GOOD_MS': 200,
    'TTFB_WARNING_MS': 500,
    'ONT_DNS': '',
    'BRAND': '',
    'NO_INTERNET': ''
}


def parse_config(config_path: Path) -> Dict[str, Any]:
    """Parse config.txt file and return configuration dictionary."""
    config = DEFAULT_CONFIG.copy()
    
    if not config_path.exists():
        return config
    
    try:
        with open(config_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' not in line:
                    continue
                
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                if key == 'TARGETS':
                    config['TARGETS'] = [t.strip() for t in value.split(',') if t.strip()]
                elif key in ['SAMPLE_COUNT', 'DELAY_SECONDS', 'PING_DURATION', 
                           'SIGNAL_THRESHOLD_DBM', 'TTFB_GOOD_MS', 'TTFB_WARNING_MS']:
                    config[key] = int(value)
                elif key == 'AUTO_CONTRIBUTE':
                    config[key] = value.lower() in ['true', '1', 'yes', 'on']
                elif key in ['ONT_DNS', 'BRAND', 'NO_INTERNET']:
                    config[key] = value
    except Exception as e:
        print(f"Error parsing config: {e}")
    
    return config


def save_config(config: Dict[str, Any], config_path: Path) -> bool:
    """Save configuration to file."""
    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(config_path, 'w') as f:
            f.write("# NOC Tune Configuration\n")
            f.write("# Auto-generated by NOC Tune UI\n")
            f.write(f"# Last updated: {datetime.now().isoformat()}\n\n")
            
            f.write("# Target URLs (comma-separated)\n")
            f.write(f"TARGETS = {', '.join(config.get('TARGETS', []))}\n\n")
            
            f.write("# Test Parameters\n")
            f.write(f"SAMPLE_COUNT = {config.get('SAMPLE_COUNT', 5)}\n")
            f.write(f"DELAY_SECONDS = {config.get('DELAY_SECONDS', 2)}\n")
            f.write(f"PING_DURATION = {config.get('PING_DURATION', 10)}\n\n")

            f.write("# Contribution\n")
            f.write(f"AUTO_CONTRIBUTE = {'True' if config.get('AUTO_CONTRIBUTE', True) else 'False'}\n\n")
            
            f.write("# Thresholds\n")
            f.write(f"SIGNAL_THRESHOLD_DBM = {config.get('SIGNAL_THRESHOLD_DBM', -70)}\n")
            f.write(f"TTFB_GOOD_MS = {config.get('TTFB_GOOD_MS', 200)}\n")
            f.write(f"TTFB_WARNING_MS = {config.get('TTFB_WARNING_MS', 500)}\n\n")
            
            f.write("# Optional: ONT DNS (fallback if auto-detect fails)\n")
            f.write(f"ONT_DNS = {config.get('ONT_DNS', '')}\n\n")

            f.write("# Optional: Contribution metadata\n")
            f.write(f"BRAND = {config.get('BRAND', '')}\n")
            f.write(f"NO_INTERNET = {config.get('NO_INTERNET', '')}\n")
        
        return True
    except Exception as e:
        print(f"Error saving config: {e}")
        return False
